on:
  schedule:
    - cron: "*/50 * * * *"
name: Update Repo
jobs:
  statsLoader:
    name: Stats Loader
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: GitHub Context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          echo "$GITHUB_CONTEXT"
      - name: Stats Loader
        uses: ./.github/actions/stats-loader
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          auth_provider_x509_cert_url: ${{ secrets.auth_provider_x509_cert_url }}
          auth_uri: ${{ secrets.auth_uri }}
          client_email: ${{ secrets.client_email }}
          client_id: ${{ secrets.client_id }}
          client_x509_cert_url: ${{ secrets.client_x509_cert_url }}
          private_key: ${{ secrets.private_key }}
          private_key_id: ${{ secrets.private_key_id }}
          project_id: ${{ secrets.project_id }}
          token_uri: ${{ secrets.token_uri }}
          type: ${{ secrets.type }}
